name: WAPM Publish
description: 'Publish to WAPM: the WebAssembly Package Manager'
author: Wasmer
branding:
  color: purple
  icon: package
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: WAPM token (https://wapm.io/settings/access-tokens)
    required: false
  username:
    description: WAPM account username
    required: false
  password:
    description: WAPM account password
    required: false
  directory:
    description: Package directory (Defaults to the current working directory)
    required: false
  registry:
    description: The registry url (defaults to https://registry.wapm.io/)
    default: https://registry.wapm.io
    required: false
